[general]
import = [ "~/.config/alacritty/base24-tomorrow-night.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 9.5
builtin_box_drawing = false
#offset = { x = 1, y = -4 }

[font.normal]
# family = "DejaVuSansM Nerd Font Mono"
# family = "Hasklug Nerd Font Mono"
family = "Iosevka Nerd Font Mono"

[font.bold]

[font.italic]

[font.bold_italic]

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
opacity = 1.0
